services:
  main-bot:
    build: .
    container_name: discord-bot-v2
    restart: always
    working_dir: /app
    volumes:
      - ./media:/app/media
    environment:
      - discordbot=${discordbot}
      - pav=${pav}
    command: python bot.py

  music-bot:
    build: .
    container_name: discord-music-bot-v2
    restart: always
    working_dir: /app
    volumes:
      - ./media:/app/media
    environment:
      - discordmusicbot=${discordmusicbot}
    command: python music.py

  web-ui:
    build: .
    container_name: discord-sound-web-v2
    restart: always
    working_dir: /app
    ports:
      - "5005:5000"
    volumes:
      - ./media:/app/media
    command: python web_ui.py


