services:
  main-bot:
    build: .
    container_name: discord-bot-v2
    restart: always
    working_dir: /app
    volumes:
      - ./media:/app/media
    environment:
      - discordbot_p1=MTE3NDM0NDgyOTgyMDQ3NzQ1MA.G9LeQ7
      - discordbot_p2=.bkB7MHVoI45TNEXEeIOamyQwfKbePjo1A2LPLA
      - discordbot2_p1=MTQ4NDYyMzc4OTk1NzQ0Nzc0Mw.G3PMWW
      - discordbot2_p2=.T2oUvz6bDG56H__hof8zXms7SlfkbIzdTNIOaU
      - pav=qZ*LP2YIgHc##oF1fGry
    command: python bot.py

  music-bot:
    build: .
    container_name: discord-music-bot-v2
    restart: always
    working_dir: /app
    volumes:
      - ./media:/app/media
    environment:
      - discordmusicbot_p1=MTE3NjA3ODI2ODQ4NzcwODcxMw.GlKw_Q
      - discordmusicbot_p2=.KwCyrxq2tNT-aPIaq8jrCPzTKF-AKMrd0rG2j8
    command: python music.py

  web-ui:
    build: .
    container_name: discord-sound-web-v2
    restart: always
    working_dir: /app
    ports:
      - "5005:5000"
    volumes:
      - ./media:/app/media
    command: python web_ui.py


